# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ssd1306')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ssd1306')
    _ssd1306 = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ssd1306', [dirname(__file__)])
        except ImportError:
            import _ssd1306
            return _ssd1306
        try:
            _mod = imp.load_module('_ssd1306', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ssd1306 = swig_import_helper()
    del swig_import_helper
else:
    import _ssd1306
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def ssd1306_begin(i2caddr):
    return _ssd1306.ssd1306_begin(i2caddr)
ssd1306_begin = _ssd1306.ssd1306_begin

def ssd1306_command(c):
    return _ssd1306.ssd1306_command(c)
ssd1306_command = _ssd1306.ssd1306_command

def ssd1306_clearDisplay():
    return _ssd1306.ssd1306_clearDisplay()
ssd1306_clearDisplay = _ssd1306.ssd1306_clearDisplay

def ssd1306_invertDisplay(i):
    return _ssd1306.ssd1306_invertDisplay(i)
ssd1306_invertDisplay = _ssd1306.ssd1306_invertDisplay

def ssd1306_display():
    return _ssd1306.ssd1306_display()
ssd1306_display = _ssd1306.ssd1306_display

def ssd1306_startscrollright(start, stop):
    return _ssd1306.ssd1306_startscrollright(start, stop)
ssd1306_startscrollright = _ssd1306.ssd1306_startscrollright

def ssd1306_startscrollleft(start, stop):
    return _ssd1306.ssd1306_startscrollleft(start, stop)
ssd1306_startscrollleft = _ssd1306.ssd1306_startscrollleft

def ssd1306_startscrolldiagright(start, stop):
    return _ssd1306.ssd1306_startscrolldiagright(start, stop)
ssd1306_startscrolldiagright = _ssd1306.ssd1306_startscrolldiagright

def ssd1306_startscrolldiagleft(start, stop):
    return _ssd1306.ssd1306_startscrolldiagleft(start, stop)
ssd1306_startscrolldiagleft = _ssd1306.ssd1306_startscrolldiagleft

def ssd1306_stopscroll():
    return _ssd1306.ssd1306_stopscroll()
ssd1306_stopscroll = _ssd1306.ssd1306_stopscroll

def ssd1306_dim(dim):
    return _ssd1306.ssd1306_dim(dim)
ssd1306_dim = _ssd1306.ssd1306_dim

def ssd1306_drawPixel(x, y, color):
    return _ssd1306.ssd1306_drawPixel(x, y, color)
ssd1306_drawPixel = _ssd1306.ssd1306_drawPixel

def ssd1306_drawFastVLine(x, y, h, color):
    return _ssd1306.ssd1306_drawFastVLine(x, y, h, color)
ssd1306_drawFastVLine = _ssd1306.ssd1306_drawFastVLine

def ssd1306_drawFastHLine(x, y, w, color):
    return _ssd1306.ssd1306_drawFastHLine(x, y, w, color)
ssd1306_drawFastHLine = _ssd1306.ssd1306_drawFastHLine

def ssd1306_fillRect(x, y, w, h, fillcolor):
    return _ssd1306.ssd1306_fillRect(x, y, w, h, fillcolor)
ssd1306_fillRect = _ssd1306.ssd1306_fillRect

def ssd1306_setTextSize(s):
    return _ssd1306.ssd1306_setTextSize(s)
ssd1306_setTextSize = _ssd1306.ssd1306_setTextSize

def ssd1306_drawString(str):
    return _ssd1306.ssd1306_drawString(str)
ssd1306_drawString = _ssd1306.ssd1306_drawString

def ssd1306_String(x, y, str, size):
    return _ssd1306.ssd1306_String(x, y, str, size)
ssd1306_String = _ssd1306.ssd1306_String

def ssd1306_drawChar(x, y, c, color, size):
    return _ssd1306.ssd1306_drawChar(x, y, c, color, size)
ssd1306_drawChar = _ssd1306.ssd1306_drawChar
# This file is compatible with both classic and new-style classes.


